slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping # or localization
    use_sim_time: false

    # SLAM Performance Fixes
    scan_queue_size: 400000000  # Increased from default 5 to avoid dropping messages
    tf_buffer_duration: 20.0  # Ensures TF synchronization, was already set correctly
    transform_timeout: 1.0  # Increased from 0.2 for better TF handling
    map_update_interval: 0.1  # Reduced from 5.0 to update the map faster

    # Debugging and Startup Config
    debug_logging: true
    throttle_scans: 0.5
    transform_publish_period: 0.02  # If set to 0, odometry won't publish
    resolution: 0.05  # Map resolution in meters
    min_laser_range: 0.5  # Minimum scan range
    max_laser_range: 100.0  # Maximum scan range
    minimum_time_interval: 0.5
    stack_size_to_use: 40000000  # Program needs a larger stack size to serialize large maps
    enable_interactive_mode: true  # Allows map editing

    # General SLAM Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 50
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

