<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.38"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_length" value="0.08"/>
    
    
   <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <inertial>
             <mass value="60" />
                <origin xyz="0.00381548 -0.00072475 0.13654259" rpy="0 0 0" />
                <inertia ixx="0.0010966742070308941" ixy="-3.7461692282368137e-07" ixz="1.9558543577840812e-07"
                        iyy="0.0017930350217347623" iyz="2.0532496529124063e-07"
                        izz="0.0025355228375863507" />
        </inertial>  
        <collision>
            <geometry>
                <box size="${base_length} 0.4 0.2"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
    
    <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="0.125" length="0.08"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/ 2.0} 0 0"/>
                <material name="grey"/>
            </visual> 
            <collision>
                <geometry>
                    <cylinder radius="0.125" length="0.08"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/ 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="10" r="0.1" h="0.05" xyz="0 0 0" rpy="${pi/ 2.0} 0 0"/>
        </link>
    </xacro:macro>
    
    <xacro:wheel_link prefix="right_front"/>
    <xacro:wheel_link prefix="left_front"/>
    <xacro:wheel_link prefix="right_back"/>
    <xacro:wheel_link prefix="left_back"/>


    <joint name="base_footprint_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel_link"/>
        <origin xyz="-0.255  ${-(base_width/ 2.0) - 0.03} 0.125" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel_link"/>
        <origin xyz="0.255  ${(base_width / 2.0) + 0.03} 0.125" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
        <joint name="base_right_back_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_back_wheel_link"/>
        <origin xyz="0.225  ${-(base_width/ 2.0) - 0.03} 0.125" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_back_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_back_wheel_link"/>
        <origin xyz="-0.225  ${(base_width / 2.0) + 0.03} 0.125" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

</robot>